/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Lab7P2_CarmenCastillo;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author casti
 */
public class PrincipalLab7 extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalLab7
     */
    public PrincipalLab7() {
        initComponents();
        this.setLocationRelativeTo(null);
        llenarLista();
        llenarListaRest();
        llenarJtreePersonasAdmin();
        llenarJtreeRestAdmin();

    }

    public static ArrayList<Usuario> listuser = new ArrayList();
    public static ArrayList<Restaurante> listrest = new ArrayList();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vCrearUsuario = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        userLabel5 = new javax.swing.JLabel();
        txt_UsuarioCU = new javax.swing.JTextField();
        userLabel6 = new javax.swing.JLabel();
        txt_ContraCU = new javax.swing.JTextField();
        btn_CrearUsuarioCU = new javax.swing.JToggleButton();
        title1 = new javax.swing.JLabel();
        userLabel7 = new javax.swing.JLabel();
        txt_NombreCU = new javax.swing.JTextField();
        vParaAdmin = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        chulo = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        userLabel11 = new javax.swing.JLabel();
        txt_nRestaurante = new javax.swing.JTextField();
        txt_Ubicacion = new javax.swing.JFormattedTextField();
        btn_addRestaurante = new javax.swing.JToggleButton();
        userLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        userLabel9 = new javax.swing.JLabel();
        txt_nProducto = new javax.swing.JTextField();
        userLabel10 = new javax.swing.JLabel();
        txt_precioP = new javax.swing.JFormattedTextField();
        btn_addProdu = new javax.swing.JToggleButton();
        cb_RestProd = new javax.swing.JComboBox<>();
        userLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lista_DelRest = new javax.swing.JList<>();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lista_TopUsuarios = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        lista_TopRest = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Restaurantes = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_Usuarios = new javax.swing.JTree();
        jToggleButton1 = new javax.swing.JToggleButton();
        vParaUsuario = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        pane1 = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        userLabel16 = new javax.swing.JLabel();
        txt_nProducto1 = new javax.swing.JTextField();
        userLabel17 = new javax.swing.JLabel();
        txt_precioP1 = new javax.swing.JFormattedTextField();
        btn_addProdu1 = new javax.swing.JToggleButton();
        cb_RestProd1 = new javax.swing.JComboBox<>();
        userLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        userLabel19 = new javax.swing.JLabel();
        btn_addProdu2 = new javax.swing.JToggleButton();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        lista_DelRest1 = new javax.swing.JList<>();
        userLabel14 = new javax.swing.JLabel();
        cb_RestProd2 = new javax.swing.JComboBox<>();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        lista_TopUsuarios1 = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        lista_TopRest1 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jt_RestaurantesUsuario = new javax.swing.JTree();
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        userLabel4 = new javax.swing.JLabel();
        txt_Usuario = new javax.swing.JTextField();
        userLabel3 = new javax.swing.JLabel();
        txt_Contra = new javax.swing.JTextField();
        btn_IniciarS = new javax.swing.JToggleButton();
        btn_CrearUsuario = new javax.swing.JToggleButton();
        btn_IniciarAdmin = new javax.swing.JToggleButton();
        userLabel8 = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(102, 0, 102));

        userLabel5.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        userLabel5.setForeground(new java.awt.Color(255, 255, 255));
        userLabel5.setText("Usuario");

        txt_UsuarioCU.setBackground(new java.awt.Color(255, 255, 255));
        txt_UsuarioCU.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_UsuarioCU.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        userLabel6.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        userLabel6.setForeground(new java.awt.Color(255, 255, 255));
        userLabel6.setText("Contraseña");

        txt_ContraCU.setBackground(new java.awt.Color(255, 255, 255));
        txt_ContraCU.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_ContraCU.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_CrearUsuarioCU.setBackground(new java.awt.Color(255, 255, 255));
        btn_CrearUsuarioCU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_CrearUsuarioCU.setForeground(new java.awt.Color(0, 0, 0));
        btn_CrearUsuarioCU.setText("Crear Usuario");
        btn_CrearUsuarioCU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CrearUsuarioCUMouseClicked(evt);
            }
        });

        title1.setFont(new java.awt.Font("Roboto Black", 1, 48)); // NOI18N
        title1.setForeground(new java.awt.Color(255, 255, 255));
        title1.setText("CREAR USUARIO");

        userLabel7.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        userLabel7.setForeground(new java.awt.Color(255, 255, 255));
        userLabel7.setText("Nombre");

        txt_NombreCU.setBackground(new java.awt.Color(255, 255, 255));
        txt_NombreCU.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_NombreCU.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(317, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(title1)
                        .addGap(326, 326, 326))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btn_CrearUsuarioCU, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(userLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(txt_UsuarioCU, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(userLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(txt_ContraCU, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(userLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(txt_NombreCU, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(274, 274, 274))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(title1)
                .addGap(81, 81, 81)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NombreCU, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_UsuarioCU, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ContraCU, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addComponent(btn_CrearUsuarioCU, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout vCrearUsuarioLayout = new javax.swing.GroupLayout(vCrearUsuario.getContentPane());
        vCrearUsuario.getContentPane().setLayout(vCrearUsuarioLayout);
        vCrearUsuarioLayout.setHorizontalGroup(
            vCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        vCrearUsuarioLayout.setVerticalGroup(
            vCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chulo.setBackground(new java.awt.Color(255, 255, 255));
        chulo.setForeground(new java.awt.Color(0, 0, 0));
        chulo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chuloStateChanged(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        userLabel11.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        userLabel11.setForeground(new java.awt.Color(0, 0, 0));
        userLabel11.setText("Nombre del Restaurante");

        txt_nRestaurante.setBackground(new java.awt.Color(204, 204, 204));
        txt_nRestaurante.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_nRestaurante.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txt_Ubicacion.setBackground(new java.awt.Color(204, 204, 204));
        txt_Ubicacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        btn_addRestaurante.setBackground(new java.awt.Color(255, 255, 255));
        btn_addRestaurante.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_addRestaurante.setForeground(new java.awt.Color(0, 0, 0));
        btn_addRestaurante.setText("Agregar Restaurante");
        btn_addRestaurante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addRestauranteMouseClicked(evt);
            }
        });

        userLabel13.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        userLabel13.setForeground(new java.awt.Color(0, 0, 0));
        userLabel13.setText("Ubicación");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_addRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(userLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(userLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nRestaurante)
                            .addComponent(txt_Ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(95, 95, 95))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(124, 124, 124)
                .addComponent(btn_addRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );

        chulo.addTab("Agregar Restaurante", jPanel7);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        userLabel9.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        userLabel9.setForeground(new java.awt.Color(0, 0, 0));
        userLabel9.setText("Nombre del Producto");

        txt_nProducto.setBackground(new java.awt.Color(204, 204, 204));
        txt_nProducto.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_nProducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        userLabel10.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        userLabel10.setForeground(new java.awt.Color(0, 0, 0));
        userLabel10.setText("Precio");

        txt_precioP.setBackground(new java.awt.Color(204, 204, 204));
        txt_precioP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        btn_addProdu.setBackground(new java.awt.Color(255, 255, 255));
        btn_addProdu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_addProdu.setForeground(new java.awt.Color(0, 0, 0));
        btn_addProdu.setText("Agregar Producto");

        userLabel12.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        userLabel12.setForeground(new java.awt.Color(0, 0, 0));
        userLabel12.setText("Restaurante a añadir producto.");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_addProdu, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(userLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nProducto)
                            .addComponent(txt_precioP, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cb_RestProd, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(95, 95, 95))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(userLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_RestProd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_precioP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(btn_addProdu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        chulo.addTab("Agregar Producto", jPanel5);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));

        jScrollPane3.setViewportView(lista_DelRest);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        chulo.addTab("Eliminar Restaurante", jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane4.setViewportView(lista_TopUsuarios);

        jScrollPane5.setViewportView(lista_TopRest);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("TOP USUARIOS");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("TOP RESTAURANTES");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(404, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(475, Short.MAX_VALUE)))
        );

        chulo.addTab("Visualización", jPanel9);

        jPanel3.add(chulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 680, 570));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jt_Restaurantes.setBackground(new java.awt.Color(255, 255, 255));
        jt_Restaurantes.setForeground(new java.awt.Color(51, 0, 51));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Restaurantes");
        jt_Restaurantes.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jt_Restaurantes);

        jt_Usuarios.setBackground(new java.awt.Color(255, 255, 255));
        jt_Usuarios.setForeground(new java.awt.Color(51, 0, 51));
        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Usuarios");
        jt_Usuarios.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(jt_Usuarios);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 340, 540));

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButton1.setText("Log Out");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        jPanel3.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, -1, -1));

        javax.swing.GroupLayout vParaAdminLayout = new javax.swing.GroupLayout(vParaAdmin.getContentPane());
        vParaAdmin.getContentPane().setLayout(vParaAdminLayout);
        vParaAdminLayout.setHorizontalGroup(
            vParaAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vParaAdminLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1078, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        vParaAdminLayout.setVerticalGroup(
            vParaAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(102, 0, 102));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pane1.setBackground(new java.awt.Color(255, 255, 255));
        pane1.setForeground(new java.awt.Color(0, 0, 0));
        pane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pane1StateChanged(evt);
            }
        });

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        userLabel16.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        userLabel16.setForeground(new java.awt.Color(0, 0, 0));
        userLabel16.setText("Nombre del Producto");

        txt_nProducto1.setBackground(new java.awt.Color(204, 204, 204));
        txt_nProducto1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_nProducto1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        userLabel17.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        userLabel17.setForeground(new java.awt.Color(0, 0, 0));
        userLabel17.setText("Precio");

        txt_precioP1.setBackground(new java.awt.Color(204, 204, 204));
        txt_precioP1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        btn_addProdu1.setBackground(new java.awt.Color(255, 255, 255));
        btn_addProdu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_addProdu1.setForeground(new java.awt.Color(0, 0, 0));
        btn_addProdu1.setText("Agregar Producto");

        userLabel18.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        userLabel18.setForeground(new java.awt.Color(0, 0, 0));
        userLabel18.setText("Usuario a modificar.");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_addProdu1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(userLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nProducto1)
                            .addComponent(txt_precioP1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cb_RestProd1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(95, 95, 95))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(userLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_RestProd1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_precioP1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(btn_addProdu1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        pane1.addTab("Modificar User", jPanel12);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        userLabel19.setFont(new java.awt.Font("Roboto Light", 1, 36)); // NOI18N
        userLabel19.setForeground(new java.awt.Color(0, 0, 0));
        userLabel19.setText("Desea eliminar su usuario?");

        btn_addProdu2.setBackground(new java.awt.Color(255, 255, 255));
        btn_addProdu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_addProdu2.setForeground(new java.awt.Color(0, 0, 0));
        btn_addProdu2.setText("Eliminar Usuario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(userLabel19)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_addProdu2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addComponent(userLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btn_addProdu2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );

        pane1.addTab("Eliminar User", jPanel2);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setForeground(new java.awt.Color(255, 255, 255));

        jScrollPane6.setViewportView(lista_DelRest1);

        userLabel14.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        userLabel14.setForeground(new java.awt.Color(0, 0, 0));
        userLabel14.setText("Restaurante a comprar producto.");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cb_RestProd2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userLabel14, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(userLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cb_RestProd2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pane1.addTab("Realizar Compra", jPanel13);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane7.setViewportView(lista_TopUsuarios1);

        jScrollPane8.setViewportView(lista_TopRest1);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("TOP USUARIOS");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("TOP RESTAURANTES");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel14Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(404, Short.MAX_VALUE)))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel14Layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(475, Short.MAX_VALUE)))
        );

        pane1.addTab("Compras Recientes", jPanel14);

        jPanel10.add(pane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 680, 570));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        jt_RestaurantesUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jt_RestaurantesUsuario.setForeground(new java.awt.Color(51, 0, 51));
        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Restaurantes");
        jt_RestaurantesUsuario.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane9.setViewportView(jt_RestaurantesUsuario);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 340, 540));

        jToggleButton2.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton2.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButton2.setText("Log Out");
        jToggleButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton2MouseClicked(evt);
            }
        });
        jPanel10.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, -1, -1));

        javax.swing.GroupLayout vParaUsuarioLayout = new javax.swing.GroupLayout(vParaUsuario.getContentPane());
        vParaUsuario.getContentPane().setLayout(vParaUsuarioLayout);
        vParaUsuarioLayout.setHorizontalGroup(
            vParaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 1078, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        vParaUsuarioLayout.setVerticalGroup(
            vParaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        title.setFont(new java.awt.Font("Roboto Black", 1, 48)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("HUGO LOG IN");

        userLabel4.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        userLabel4.setForeground(new java.awt.Color(255, 255, 255));
        userLabel4.setText("Usuario");

        txt_Usuario.setBackground(new java.awt.Color(255, 255, 255));
        txt_Usuario.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_Usuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        userLabel3.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        userLabel3.setForeground(new java.awt.Color(255, 255, 255));
        userLabel3.setText("Password:");

        txt_Contra.setBackground(new java.awt.Color(255, 255, 255));
        txt_Contra.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_Contra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_IniciarS.setBackground(new java.awt.Color(255, 255, 255));
        btn_IniciarS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_IniciarS.setForeground(new java.awt.Color(0, 0, 0));
        btn_IniciarS.setText("Iniciar Sesion");
        btn_IniciarS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_IniciarSMouseClicked(evt);
            }
        });

        btn_CrearUsuario.setBackground(new java.awt.Color(255, 255, 255));
        btn_CrearUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_CrearUsuario.setForeground(new java.awt.Color(0, 0, 0));
        btn_CrearUsuario.setText("Crear Usuario");
        btn_CrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CrearUsuarioMouseClicked(evt);
            }
        });

        btn_IniciarAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btn_IniciarAdmin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_IniciarAdmin.setForeground(new java.awt.Color(0, 0, 0));
        btn_IniciarAdmin.setText("Iniciar Sesión como Administrador");
        btn_IniciarAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_IniciarAdminMouseClicked(evt);
            }
        });

        userLabel8.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        userLabel8.setForeground(new java.awt.Color(255, 255, 255));
        userLabel8.setText("ó");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(303, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(userLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(txt_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(288, 288, 288))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(userLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(txt_Contra, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(364, 364, 364))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_IniciarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_IniciarS, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(477, 477, 477))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(userLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(525, 525, 525))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_IniciarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(title)
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Contra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(btn_IniciarS, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_IniciarAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_IniciarAdminMouseClicked
        this.setVisible(false);
        vParaAdmin.pack();
        vParaAdmin.setLocationRelativeTo(null);
        vParaAdmin.setVisible(true);
        llenarLista();
        llenarListaRest();
        llenarJtreePersonasAdmin();
        llenarJtreeRestAdmin();
        llenarJtreeRestUsuarios();
    }//GEN-LAST:event_btn_IniciarAdminMouseClicked

    private void btn_CrearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CrearUsuarioMouseClicked
        this.setVisible(false);
        vCrearUsuario.pack();
        vCrearUsuario.setLocationRelativeTo(null);
        vCrearUsuario.setVisible(true);
    }//GEN-LAST:event_btn_CrearUsuarioMouseClicked

    private void btn_IniciarSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_IniciarSMouseClicked
        boolean correct = false;
        for (int i = 0; i < listuser.size(); i++) {
            if (listuser.get(i).getUsuario().equals(txt_Usuario.getText()) && listuser.get(i).getContra().equals(txt_Contra.getText())) {
                this.setVisible(false);
                vParaUsuario.pack();
                vParaUsuario.setLocationRelativeTo(null);
                vParaUsuario.setVisible(true);
                correct = true;
            }
        }
        if (!correct) {
            JOptionPane.showMessageDialog(null, "Usuario y/o Contraseña incorrectos.");
            txt_Usuario.setText("");
            txt_Contra.setText("");
        }

        AdministrarUsuarios ap = new AdministrarUsuarios("./Usuarios.txt");
        ap.cargarArchivo();
        for (Usuario usuario : ap.getListaUser()) {
            System.out.println(usuario);
        }

    }//GEN-LAST:event_btn_IniciarSMouseClicked

    private void btn_CrearUsuarioCUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CrearUsuarioCUMouseClicked
        boolean usuarioRep = false;
        for (int i = 0; i < listuser.size(); i++) {

            if (txt_UsuarioCU.getText().equals(listuser.get(i).getUsuario())) {
                JOptionPane.showMessageDialog(null, "¡Este usuario ya existe!");
                usuarioRep = true;
            }

        }

        if (!usuarioRep) {
            AdministrarUsuarios ap = new AdministrarUsuarios("./Usuarios.txt");
            ap.cargarArchivo();
            Usuario u = new Usuario(txt_NombreCU.getText(), txt_UsuarioCU.getText(), txt_ContraCU.getText(), 0);
            ap.getListaUser().add(u);
            try {
                ap.escribirArchivo();
            } catch (IOException ex) {
                Logger.getLogger(PrincipalLab7.class.getName()).log(Level.SEVERE, null, ex);
            }

//            DefaultTreeModel modeloARBOL = (DefaultTreeModel) jt_Usuarios.getModel();
//            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
//
//            int centinela = -1;
//            for (int i = 0; i < raiz.getChildCount(); i++) {
//                if (raiz.getChildAt(i).toString().equals(txt_NombreCU.getText())) {
//                    DefaultMutableTreeNode us = new DefaultMutableTreeNode(u.getUsuario());
//                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(us);
//                    centinela = 1;
//                } //fin if
//            } //fin for  
//
//            if (centinela == -1) {
//                DefaultMutableTreeNode p = new DefaultMutableTreeNode(u.getNombre());
//                DefaultMutableTreeNode us = new DefaultMutableTreeNode(u.getUsuario());
//                p.add(us);
//                raiz.add(p);
//            }  // fin if          
//            modeloARBOL.reload();
//
            txt_NombreCU.setText("");
            txt_UsuarioCU.setText("");
            txt_ContraCU.setText("");
            JOptionPane.showMessageDialog(null, "¡Usuario Creado!");
            vCrearUsuario.pack();
            vCrearUsuario.setLocationRelativeTo(null);
            vCrearUsuario.setVisible(false);
            this.setVisible(true);
        }
    }//GEN-LAST:event_btn_CrearUsuarioCUMouseClicked

    private void llenarLista() {
        AdministrarUsuarios ap = new AdministrarUsuarios("./Usuarios.txt");
        ap.cargarArchivo();
        for (Usuario v : ap.getListaUser()) {
            listuser.add(v);
        }
    }

    private void llenarListaRest() {
        AdminRestaurante ap = new AdminRestaurante("./Restaurantes.txt");
        ap.cargarArchivo();
        for (Restaurante v : ap.getListRest()) {
            listrest.add(v);
        }
    }

    private void llenarJtreeRestAdmin() {
        AdminRestaurante ap = new AdminRestaurante("./Restaurantes.txt");
        ap.cargarArchivo();
        for (Restaurante upa : ap.getListRest()) {
            DefaultTreeModel modeloARBOL = (DefaultTreeModel) jt_Restaurantes.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();

            int centinela = -1;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if (raiz.getChildAt(i).toString().equals(upa.getNombre())) {
                    DefaultMutableTreeNode us = new DefaultMutableTreeNode(upa.getUbicacion());
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(us);
                    centinela = 1;
                } //fin if
            } //fin for  

            if (centinela == -1) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(upa.getNombre());
                DefaultMutableTreeNode us = new DefaultMutableTreeNode(upa.getUbicacion());
                p.add(us);
                raiz.add(p);
            }  // fin if          
            modeloARBOL.reload();
        }

    }
    
    private void llenarJtreeRestUsuarios() {
        AdminRestaurante ap = new AdminRestaurante("./Restaurantes.txt");
        ap.cargarArchivo();
        for (Restaurante upa : ap.getListRest()) {
            DefaultTreeModel modeloARBOL = (DefaultTreeModel) jt_RestaurantesUsuario.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();

            int centinela = -1;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if (raiz.getChildAt(i).toString().equals(upa.getNombre())) {
                    DefaultMutableTreeNode us = new DefaultMutableTreeNode(upa.getUbicacion());
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(us);
                    centinela = 1;
                } //fin if
            } //fin for  

            if (centinela == -1) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(upa.getNombre());
                DefaultMutableTreeNode us = new DefaultMutableTreeNode(upa.getUbicacion());
                p.add(us);
                raiz.add(p);
            }  // fin if          
            modeloARBOL.reload();
        }

    }

    private void llenarJtreePersonasAdmin() {
        AdministrarUsuarios ap = new AdministrarUsuarios("./Usuarios.txt");
        ap.cargarArchivo();
        for (Usuario upa : ap.getListaUser()) {
            DefaultTreeModel modeloARBOL = (DefaultTreeModel) jt_Usuarios.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();

            int centinela = -1;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if (raiz.getChildAt(i).toString().equals(upa.getNombre())) {
                    DefaultMutableTreeNode us = new DefaultMutableTreeNode(upa.getUsuario());
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(us);
                    centinela = 1;
                } //fin if
            } //fin for

            if (centinela == -1) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(upa.getNombre());
                DefaultMutableTreeNode us = new DefaultMutableTreeNode(upa.getUsuario());
                p.add(us);
                raiz.add(p);
            }  // fin if          
            modeloARBOL.reload();
        }

    }

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        vParaAdmin.pack();
        vParaAdmin.setLocationRelativeTo(null);
        vParaAdmin.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void btn_addRestauranteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addRestauranteMouseClicked

        boolean RestRep = false;
        for (int i = 0; i < listrest.size(); i++) {

            if (txt_nRestaurante.getText().equals(listrest.get(i).getNombre())) {
                JOptionPane.showMessageDialog(null, "¡Este restaurante ya existe!");
                RestRep = true;
            }
//me duele la espalde
        }

        if (!RestRep) {
            AdminRestaurante ap = new AdminRestaurante("./Restaurantes.txt");
            ap.cargarArchivo();
            Restaurante u = new Restaurante(txt_nRestaurante.getText(), txt_Ubicacion.getText(), 0);
            ap.getListRest().add(u);
            try {
                ap.escribirArchivo();
            } catch (IOException ex) {
                Logger.getLogger(PrincipalLab7.class.getName()).log(Level.SEVERE, null, ex);
            }
            txt_nRestaurante.setText("");
            txt_Ubicacion.setText("");
            JOptionPane.showMessageDialog(null, "¡Restaurante Creado!");

        }

    }//GEN-LAST:event_btn_addRestauranteMouseClicked

    private void chuloStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chuloStateChanged
        AdminRestaurante ap = new AdminRestaurante("./Restaurantes.txt");
        ap.cargarArchivo();
        cb_RestProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));
        for (Restaurante c : ap.getListRest()) {
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_RestProd.getModel();
            modelo.addElement(c);
            cb_RestProd.setModel(modelo);
        }

    }//GEN-LAST:event_chuloStateChanged

    private void pane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pane1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_pane1StateChanged

    private void jToggleButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton2MouseClicked
        vParaUsuario.pack();
        vParaUsuario.setLocationRelativeTo(null);
        vParaUsuario.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jToggleButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalLab7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalLab7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalLab7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalLab7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalLab7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_CrearUsuario;
    private javax.swing.JToggleButton btn_CrearUsuarioCU;
    private javax.swing.JToggleButton btn_IniciarAdmin;
    private javax.swing.JToggleButton btn_IniciarS;
    private javax.swing.JToggleButton btn_addProdu;
    private javax.swing.JToggleButton btn_addProdu1;
    private javax.swing.JToggleButton btn_addProdu2;
    private javax.swing.JToggleButton btn_addRestaurante;
    private javax.swing.JComboBox<String> cb_RestProd;
    private javax.swing.JComboBox<String> cb_RestProd1;
    private javax.swing.JComboBox<String> cb_RestProd2;
    private javax.swing.JTabbedPane chulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTree jt_Restaurantes;
    private javax.swing.JTree jt_RestaurantesUsuario;
    private javax.swing.JTree jt_Usuarios;
    private javax.swing.JList<String> lista_DelRest;
    private javax.swing.JList<String> lista_DelRest1;
    private javax.swing.JList<String> lista_TopRest;
    private javax.swing.JList<String> lista_TopRest1;
    private javax.swing.JList<String> lista_TopUsuarios;
    private javax.swing.JList<String> lista_TopUsuarios1;
    private javax.swing.JTabbedPane pane1;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JTextField txt_Contra;
    private javax.swing.JTextField txt_ContraCU;
    private javax.swing.JTextField txt_NombreCU;
    private javax.swing.JFormattedTextField txt_Ubicacion;
    private javax.swing.JTextField txt_Usuario;
    private javax.swing.JTextField txt_UsuarioCU;
    private javax.swing.JTextField txt_nProducto;
    private javax.swing.JTextField txt_nProducto1;
    private javax.swing.JTextField txt_nRestaurante;
    private javax.swing.JFormattedTextField txt_precioP;
    private javax.swing.JFormattedTextField txt_precioP1;
    private javax.swing.JLabel userLabel10;
    private javax.swing.JLabel userLabel11;
    private javax.swing.JLabel userLabel12;
    private javax.swing.JLabel userLabel13;
    private javax.swing.JLabel userLabel14;
    private javax.swing.JLabel userLabel16;
    private javax.swing.JLabel userLabel17;
    private javax.swing.JLabel userLabel18;
    private javax.swing.JLabel userLabel19;
    private javax.swing.JLabel userLabel3;
    private javax.swing.JLabel userLabel4;
    private javax.swing.JLabel userLabel5;
    private javax.swing.JLabel userLabel6;
    private javax.swing.JLabel userLabel7;
    private javax.swing.JLabel userLabel8;
    private javax.swing.JLabel userLabel9;
    private javax.swing.JDialog vCrearUsuario;
    private javax.swing.JDialog vParaAdmin;
    private javax.swing.JDialog vParaUsuario;
    // End of variables declaration//GEN-END:variables
}
